# Generated by Django 2.1.4 on 2019-09-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.CharField(max_length=1),
        ),
    ]
